// includes
#include <EigenTenxor>
#include <IDNTensor>

// Preprocessor Decls
#define __PI 3.1415

// Beim Programm aufruf übergeben Argumente
input size         argc;
input stringVec    argv;

// uniforms die extern gesetzt werden können
uniform pID         processID;
uniform Logfile     fLog;

// output Ports
ofstream port IDNTensor     tIDN;
ofstream port Texture       ltxFormula;

// forward Deklarationen
fwddecl proc main;
fwddecl proc terminateSelf;

decl proc main(){

    //
    staticExpr tensor[4]{...} E;
    staticExpr tensor[2]{...} C;
    staticDecl tensor[1]{...} u;
    
    //
    TensorExpr f = E .. C : u
    
    //
    IDNTensor fIDN = convertToIDN(f);
    
    //
    IDNTensor dfIDN = diff(fIDN, u);
    
    //
    push [IDNTensor]     dfIDN;
    push [ltxFormula]    convertToLTXTexture(dfIDN);
    
    //
    flush ofstreams;
};