struct Vector3{
    
    static{
    
        int[a,b]
        
        decl printStatics(){
            log(a, b)
        }
        
        decl getA(){
            return a
        }
        
        decl getB(){
            return b
        }
    }
    
    double[x,y,z]
    
    decl getX(){
        return [x]
    }
}

decl __addAssign__(Vector3 ref a, Vector3 ref b){
    
    //
    a->[x,y,z] += b->[x,y,z]
}

int g_EnvVar = 5

decl test(){
    return g_EnvVar
}

//
decl main(){
    
    Vector3 [vec, vec2]
    
    vec->[x, y, z] = 1.0, 2.0, 3.0
    vec2->[x, y, z] = 1.0, 2.0, 3.0
    Vector3 >> a, Vector3 >> b = 5, 6
    
    logRes(vec->getX())

    return 0
}

if(calledAs(__MainProc__)){
    return[main()]
}